### ISSUE TITLE
thread '<unnamed>' panicked at 'cannot access stdout during shutdown'

### ISSUE THREAD

**Issue by pakipaki2000** [AltSysrq/lmdb-zero#16]
Hi,

Thanks for the lib :)
Looks like I can't open an environnement inside a thread or even outside, how do you pass the env variable to a thread?

CODE =
  let env = unsafe {

      		let mut env_builder = lmdb::EnvBuilder::new().unwrap();
                env_builder.set_mapsize(54975188).unwrap_or_else(|e| {
                    panic!("Unable to allocate LMDB space: {:?}", e);
                });

            env_builder.open(
            "/dev/shm/dbs0", lmdb::open::Flags::empty(), 0o600).unwrap()
    };

    let go = thread::spawn(move || {
    example(&format!("/dev/shm/dbs{:?}", 0), env); // Don't mind this function, I've just put a println inside
 });

It keep saying:
thread '<unnamed>' panicked at 'cannot access stdout during shutdown', src/libcore/option.rs:1038:5

I tried putting both env variable INSIDE the thread and also OUTSIDE the thread, I don't think I understand why it's working just fine but if I move my whole thing inside a thread it's not working anymore.

PS: Tried also with a mutable &mut env... doesn't work.

Thanks for the help :)

**Comment by AltSysrq** [comment]
I think something else is going on. I adapted your example, and this code works regardless of whether or not `main` calls `.join().unwrap()` on the thread handle: https://gist.github.com/AltSysrq/2dbd2aa891554955409dba08fe979a34 (The body of `do_stuff` was copied from the crate docs; the `sleep_ms()` call is to ensure the main thread exits before the thread actually does anything)

Have you tried running with `RUST_BACKTRACE=1` to get more information about where exactly the panic is happening?

Unfortunately I'm not really sure what to suggest. The error message appears to correspond to this bug: https://github.com/rust-lang/rust/issues/29488. Some of the comments mention it being platform-dependent; but I was running my test on Linux, and your paths also look Linux-specific to me.

`lmdb-zero` doesn't use any TLS nor does it have any `println!`s (much less one in a `Drop` implementation), so I think there's a chance your issue isn't actually related to LMDB but instead is elsewhere and spawning the extra thread perturbs the timing of things just right for you to run into the problem.

**Comment by pakipaki2000** [comment]
Thank you for the answer! Very helpful.

It's weird because:

fn main() {
    let env = unsafe {
      	let mut env_builder = lmdb::EnvBuilder::new().unwrap();
        env_builder.set_mapsize(54975188).unwrap_or_else(|e| {
            panic!("Unable to allocate LMDB space: {:?}", e);
        });

        env_builder.open(
            "/dev/shm/dbs", lmdb::open::Flags::empty(), 0o600).unwrap()
    };

    thread::spawn(move || {
        println!("yoop");
        do_stuff(env);
    });
}
The println! doesn't show anything, it compile just fine but doesn't show the println!, how is it possible?

**Comment by pakipaki2000** [comment]
Thank you!
The problem was because my program was exiting before the thread finished!

Very helpful, have a nice day
