### ISSUE TITLE
Inserting Struct, problem with LmdbRaw

### ISSUE THREAD

**Issue by pakipaki2000** [AltSysrq/lmdb-zero#20]
Hi,

I'm having troubles inserting deep Structures (structs inside structs).

```
#[repr(C, packed)]
#[derive(Copy, Clone,Debug)]
pub struct DBC {
    Vector: DBC_Vector,
    Settings: DBC_Settings,
    Globals: Vec<StorageType>,
    DBName: HashedString, 
}

unsafe impl lmdb::traits::LmdbRaw for DBC { }


```

Problem here is It seems I can't insert that Vec (because of Copy), and if I remove Copy then it asks 
label: the trait `std::marker::Copy` is not implemented for `DBC`

Can you make a working example about how to insert a Struct with a Vec inside (and other structs), would be awesome, thanks! :)

**Comment by HandleMaser** [comment]
I've actually got the same issue a while ago, I ended-up inserting a fix Array inside of a Vector. kinda sucks :/

I don't think lmdb-zero can insert Vectors unfortunately

**Comment by AltSysrq** [comment]
You absolutely cannot use things like `Vec`s with `LmdbRaw` because they contain pointers to their data. You'll need to use a serialisation system like serde to convert to and from byte arrays first.

**Comment by pakipaki2000** [comment]
Hi AltSysrq!

Thank you for the answer.
I guess that would be the same if I were to insert a hashmap inside a value?

Thank you.

**Comment by AltSysrq** [comment]
Yes. Even if you were allowed to mark it `LmdbRaw`, it still wouldn't work because your data isn't _inside_ your struct.

If it helps illustrate, here's an example of what's going on:

```rust
use std::mem;
use std::slice;

#[repr(C)]
struct Example {
    foo: i32,
    bar: i32,
    vec: Vec<i32>,
}

fn main() {
    let example = Example {
        foo: 42,
        bar: 1000,
        vec: vec![1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    };

    // This is exactly what `LmdbRaw` causes to happen
    // We're getting the raw byte representation of the struct
    let example_bytes = unsafe {
        slice::from_raw_parts(
            (&example) as *const Example as *const u8,
            mem::size_of::<Example>())
    };

    println!("Example bytes: {:?}", example_bytes);
}
```

Here's an example of output it might produce (which varies by CPU architecture). I added some formatting and comments to show what things mean.

```
Example bytes: [
  42, 0, 0, 0,                          foo: 42i32
  232, 3, 0, 0,                         bar: 1000i32
  64, 42, 11, 136, 123, 85, 0, 0,       pointer inside vec to array base
  10, 0, 0, 0, 0, 0, 0, 0,              length of vec
  10, 0, 0, 0, 0, 0, 0, 0               capacity of vec
]
```

Notice that the actual content of `vec` is nowhere to be found because it's only referenced by that pointer.

**Comment by pakipaki2000** [comment]
Amazing explanation! Thank you AltSysrq for your time.
You are a nice guy.

Please forward me your Bitcoin address I might do a small donation :)
