### ISSUE TITLE
Isn't possible to use enums?

### ISSUE THREAD

**Issue by nappa85** [AltSysrq/lmdb-zero#24]
Hello,
I was doing a simple experiment, using a simple enum like that:
```
#[repr(C)]
#[derive(Clone,Copy,Debug,PartialEq,Eq)]
enum MyEnum<'a> {
    A(&'a Unaligned<u32>),
    B(&'a Unaligned<u64>),
}

unsafe impl<'a> LmdbRaw for MyEnum<'a> {
    fn reported_type() -> String {
        String::from("MyEnum")
    }
}
```

The program compiles fine, and seems to write without problems, but as soon I try to read, i receive the error "Error::ValRejected("Type MyEnum is size 16, but byte array has size 8")"

Isn't it possible to use enums with lmdb_zero?

**Comment by AltSysrq** [comment]
`MyEnum` fails the [requirements for `LmdbRaw`](https://docs.rs/lmdb-zero/0.4.4/lmdb_zero/traits/trait.LmdbRaw.html#unsafety) on multiple fronts.

> Behaviour is undefined if there exist bit patterns of the same size of the type which are not valid instances of that type unless the client code can somehow guarantee that such bit patterns do not occur. … Of particular note, `bool` and essentially all enum types are not sensible for use with `LmdbRaw` (directly or within composites) because they are only valid for particular bit patterns.

> If the tagged type contains pointers of any kind, they will be stored in and retrieved from the database, which has serious ramifications … If the type contains Rust references, this will almost certainly lead to undefined behaviour.

From your enum definition and error message, it almost sounds like you're writing in bare integers and then trying to read `MyEnum` back? In that case, what you want to do is read in the bare integers and wrap them in `MyEnum` yourself.

**Comment by nappa85** [comment]
I've made a simple test:
```
println!("{:?}", MyEnum::A(unaligned(&10u32)).as_lmdb_bytes());
println!("{:?}", MyEnum::B(unaligned(&25u64)).as_lmdb_bytes());
```
prints
```
[0, 0, 0, 0, 225, 127, 0, 0, 4, 16, 147, 219, 68, 86, 0, 0]
[1, 0, 0, 0, 254, 127, 0, 0, 8, 16, 147, 219, 68, 86, 0, 0]
```
which, I hope, should be correct.
But then, with this simple code:
```
    let txn = WriteTransaction::new(context.env.clone()).unwrap();
    {
        let mut access = txn.access();
        access.put(&context.db, &[1u8], &MyEnum::A(unaligned(&10u32)), Flags::empty()).unwrap();
        access.put(&context.db, &[2u8], &MyEnum::B(unaligned(&25u64)), Flags::empty()).unwrap();
    }
    txn.commit().unwrap();

    let txn = ReadTransaction::new(context.env.clone()).unwrap();
    {
        let access = txn.access();
        let mut cursor = txn.cursor(context.db.clone()).unwrap();
        let res1: Option<(&[u8], &MyEnum)> = cursor.first(&access).to_opt().unwrap();
        println!("First: {:?}", res1);
        let res2: Option<&MyEnum> = cursor.last_dup(&access).to_opt().unwrap();
        println!("First::last_dup: {:?}", res2);
        let res3: Option<(&[u8], &MyEnum)> = cursor.next(&access).to_opt().unwrap();
        println!("Next: {:?}", res3);
        let res4: Option<&MyEnum> = cursor.last_dup(&access).to_opt().unwrap();
        println!("Next::last_dup: {:?}", res4);
    }
```
I have a misalignment error:
```
Error::ValRejected("Type MyEnum requires alignment 8, but byte array at 7f341a3e1fef is misaligned by 7 bytes (see https://docs.rs/lmdb-zero/0.4.4/lmdb_zero/traits/trait.LmdbRaw.html#alignment)")
```

**Comment by AltSysrq** [comment]
> prints
> 
> ```
> [0, 0, 0, 0, 225, 127, 0, 0, 4, 16, 147, 219, 68, 86, 0, 0]
> [1, 0, 0, 0, 254, 127, 0, 0, 8, 16, 147, 219, 68, 86, 0, 0]
> ```
> 
> which, I hope, should be correct.

Without looking at your own code, can you say whether `254, 127, 0, 0, 8, 16, 147, 219, 68, 86, 0, 0` represents 10 or 25?

---

I'd really recommend using serde or something similar to turn your values to and from byte arrays. Defining your own `LmdbRaw` types is fairly advanced usage and (please don't take this the wrong way) requires a solid understanding of how data types are represented at a low level, and LMDB isn't a great place to learn that.

**Comment by nappa85** [comment]
Yes, it's what I'm doing with bincode, but I was trying to find a cleaner way that doesn't involve serializing and deserializing "manually" before every insertion and retrieve.

**Comment by AltSysrq** [comment]
That's why the docs contain this note:

> _This is not a general-purpose deserialisation mechanism._ There is no way to use this trait to read values in any format other than how they are natively represented in memory. The only control is that outright invalid values can be rejected so as to avoid undefined behaviour from, eg, constructing `&strs` with malformed content. Reading values not in native format requires extracting the byte slice and using a separate deserialisation mechanism.

`FromLmdbBytes` / `ToLmdbBytes` / `LmdbRaw` / etc are nothing more than a thin layer for types that can be safely coerced (a la `std::mem::transmute`) directly to and from byte arrays without parsing.

**Comment by nappa85** [comment]
Ok, thank you for your support.


Best regards
