### ISSUE TITLE
Strange behaviour with INTEGERKEY and DUPSORT

### ISSUE THREAD

**Issue by nappa85** [AltSysrq/lmdb-zero#25]
Hello,
I'm experiencing an unexpected behaviuor when using INTEGERKEY along with DUPSORT.
```
use std::sync::Arc;
use std::fs::{read_dir, create_dir_all};

use lmdb_zero::{Environment, Database, EnvBuilder, DatabaseOptions, open, db, put::Flags, ReadTransaction, WriteTransaction, traits::LmdbResultExt};

pub struct LmdbContext {
    pub env: Arc<Environment>,
    pub db: Arc<Database<'static>>,
}

fn lmdb_db_build_context(path_db: &str) -> LmdbContext {
    let env = Arc::new(unsafe {
        let mut env_builder = EnvBuilder::new().expect("1");
        env_builder.set_mapsize(4_000_000).expect("2");
        // check if dir exists
        if read_dir(path_db).is_err() {
            // create dir
            create_dir_all(path_db).expect("3");
        }
        env_builder.open(path_db, open::Flags::empty(), 0o600).expect("4")
    });

    let db = Arc::new(Database::open(
        Arc::clone(&env),
        None,
        &DatabaseOptions::new(db::DUPSORT | db::INTEGERKEY | db::CREATE)).expect("5"));

    LmdbContext {
        env,
        db,
    }
}

fn main() {
    let context = lmdb_db_build_context("test");

    let txn = WriteTransaction::new(context.env.clone()).expect("1");
    {
        let mut access = txn.access();
        access.put(&context.db, &[1u8], &[1u8], Flags::empty()).expect("2");
        access.put(&context.db, &[2u8], &[2u8], Flags::empty()).expect("3");
        access.put(&context.db, &[2u8], &[3u8], Flags::empty()).expect("4");
    }
    txn.commit().expect("5");

    let txn = ReadTransaction::new(context.env.clone()).expect("6");
    {
        let access = txn.access();
        let mut cursor = txn.cursor(context.db.clone()).expect("7");
        let res1: Option<(&[u8], &[u8])> = cursor.first(&access).to_opt().expect("8");
        println!("First: {:?}", res1);
        let res2: Option<&[u8]> = cursor.last_dup(&access).to_opt().expect("9");
        println!("First::last_dup: {:?}", res2);
        let res3: Option<(&[u8], &[u8])> = cursor.next(&access).to_opt().expect("10");
        println!("Next: {:?}", res3);
        let res4: Option<&[u8]> = cursor.last_dup(&access).to_opt().expect("11");
        println!("Next::last_dup: {:?}", res4);
    }
}
```
What I expect from this code is
```
First: Some(([1], [1]))
First::last_dup: Some([1])
Next: Some(([2], [2]))
Next::last_dup: Some([3])
```
instead I get
```
First: Some(([1], [1]))
First::last_dup: Some([1])
Next: Some(([2], [2]))
Next::last_dup: Some([2])
```

Taking out INTEGERKEY it works as expected.

**Comment by nappa85** [comment]
I made some other tests, seems like some Flags combinations are ignored, and obviosly some are invalid.
Some examples:
* DUPSORT | INTEGERKEY => works, but DUPSORT is ignored
* DUPSORT | INTEGERDUP => works as expected
* INTEGERKEY | INTEGERDUP => invalid

Maybe the docs about Flags could be expanded a little

**Comment by AltSysrq** [comment]
https://docs.rs/lmdb-zero/0.4.4/lmdb_zero/db/constant.INTEGERKEY.html

> Keys are binary integers in native byte order, either `libc::c_uint` or `libc::size_t`, and will be sorted as such. The keys must all be of the same size.

Using byte arrays with `INTEGERKEY` isn't generally going to produce reasonable results. I actually didn't think LMDB would have allowed your 1-byte keys since they are not the same size as either of those types and I'm not sure what exactly it _is_ doing with them, though my guess is that they're getting zero-padded to the right. Or maybe it's corrupting the database and the example doesn't do enough for it to notice.

> docs

I don't actually know the valid combinations myself — in general, the docs that exist are just copied from the LMDB docs and edited to use rust syntax and lmdb-zero names, plus a simple example illustrating how to use the feature with lmdb-zero.

**Comment by nappa85** [comment]
Yes, I checked also the LMDB docs and there are no valid or invalid combinations listed, as far as I can see.
Anyway I'm closing this issue since it has solved as upstream missing docs.
