### ISSUE TITLE
Question: alignment inside lmdb

### ISSUE THREAD

**Issue by hh9527** [AltSysrq/lmdb-zero#8]
if all size of keys and values are aligned to byte8, will lmdb guarantee address of fetched key/values are aligned by byte8?

**Comment by AltSysrq** [comment]
It is not guaranteed. LMDB only guarantees that the key data will be aligned to 2 bytes, and the corresponding value will be as well _if_ the key data is an even number of bytes wide.

On a system with 64-bit pointers you may find you do get the desired alignment anyway by happy coincidence of the page header being 16 bytes wide and the node header being 8 bytes wide. This is not the case for 32-bit systems though

In any case, I would advise against depending on this unless you're willing to pin to one architecture and can easily switch away if this doesn't actually work out.

**Comment by hh9527** [comment]
Thank you for your explaination

I am working on a state management system in which read performance is the key point.

For keys, there need to have a encoding/decoding step. So alignment maybe not necessary.
But for values, it better to have an alignment guarantee.

For now, I have a workaround idea like this:
when put values: use `put_reserve_array` to get a pre-allocated value buffer which is larger than the value.len(), then fill it with a leading padding and a tail padding to adjust the offset of value data to aligned.

```
    (key data)  (1 byte)  (pad-left)  (value data)  (pad-right)
    ^align-b2   ^                     ^align-b8               ^align-b8
                no-alignment
                indicate the size of pad-left and pad-right
```

Is it works?

**Comment by AltSysrq** [comment]
Not quite, unfortunately, since LMDB may move the nodes around as items are added to / removed from the database.

In theory, there's a function you could use to manually maintain the alignment when this happens. Unfortunately, it doesn't actually do anything right now:

```c
	/** @brief Set a relocation function for a #MDB_FIXEDMAP database.
	 *
	 * @todo The relocation function is called whenever it is necessary to move the data
	 * of an item to a different position in the database (e.g. through tree
	 * balancing operations, shifts as a result of adds or deletes, etc.). It is
	 * intended to allow address/position-dependent data items to be stored in
	 * a database in an environment opened with the #MDB_FIXEDMAP option.
	 * Currently the relocation feature is unimplemented and setting
	 * this function has no effect.
	 * @param[in] txn A transaction handle returned by #mdb_txn_begin()
	 * @param[in] dbi A database handle returned by #mdb_dbi_open()
	 * @param[in] rel A #MDB_rel_func function
	 * @return A non-zero error value on failure and 0 on success. Some possible
	 * errors are:
	 * <ul>
	 *	<li>EINVAL - an invalid parameter was specified.
	 * </ul>
	 */
int  mdb_set_relfunc(MDB_txn *txn, MDB_dbi dbi, MDB_rel_func *rel);
```

I have no idea if this makes sense for your values, but there are [some ways for reducing the alignment requirements of structs](https://docs.rs/lmdb-zero/0.3.1/lmdb_zero/traits/trait.LmdbRaw.html#alignment) that may be worth considering if you haven't already.

**Comment by hh9527** [comment]
@AltSysrq thank you for your explanation, finally I use a unaligned wrap, with cow.

**Comment by AltSysrq** [comment]
It sounds like the problem has been answered, so closing this. Please feel free to reopen if I misunderstood.
