### ISSUE TITLE
Open database in read-only environment?

### ISSUE THREAD

**Issue by cmbrandenburg** [AltSysrq/lmdb-zero#9]
Is it possible to use `lmdb_zero` to open a database in an environment that's read-only? If so, I can't figure out how.

I'm looking at the [`Database::open`](https://docs.rs/lmdb-zero/0.4.1/lmdb_zero/struct.Database.html#method.open) method, which indiscriminately opens a read-write transaction. Consequently, it returns a “Permissions denied” error.

Perhaps the `open` method should open a read-only transaction if the `db::CREATE` flag is not specified.

**Comment by cmbrandenburg** [comment]
My idea to use `db::CREATE` to determine whether the database is read-only is probably a really bad idea. Maybe instead just provide another method, a la `open_read_only`?

**Comment by AltSysrq** [comment]
The fix for this (via #10) is published in 0.4.2.

**Comment by cmbrandenburg** [comment]
Thanks!
